/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugasakhir.main;

import com.tugasakhir.koneksi.koneksi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author TubagusR
 */
public class transaksi extends javax.swing.JFrame {
    Statement stt;
    Statement stt2;
    ResultSet rss;
    DefaultTableModel model;
    String tgl;
    /**
     * Creates new form report
     */
    public transaksi() {
        initComponents();
//        tabel_makanan();
        tampil_tabel();
        tabel_transaksi();
        tampil_tabel_transaksi();
        tglskrg();
        no_transaksi();
        kode_makanan();
        this.setLocationRelativeTo(null);
    }
    public JTextField id_kasir(){
        return txt_id_kasir;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id_kasir = new javax.swing.JTextField();
        tgl_transaksi = new javax.swing.JTextField();
        txt_no_transaksi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmb_kode = new javax.swing.JComboBox<>();
        txt_nama_paket = new javax.swing.JTextField();
        txt_harga_t = new javax.swing.JTextField();
        txt_jumlah_t = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_total_semua = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI");

        jLabel2.setText("Id Admin");

        jLabel3.setText("Tanggal Transaksi");

        jLabel4.setText("No Transaksi");

        jLabel5.setText("Kode Paket Makanan");

        jLabel6.setText("Kode Paket Makanan");

        jLabel7.setText("Harga");

        jLabel8.setText("Jumlah");

        txt_id_kasir.setEditable(false);
        txt_id_kasir.setText("2");
        txt_id_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_kasirActionPerformed(evt);
            }
        });

        tgl_transaksi.setEditable(false);

        txt_no_transaksi.setEditable(false);

        jButton1.setText("Transaksi Selanjutnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmb_kode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kodeItemStateChanged(evt);
            }
        });
        cmb_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kodeActionPerformed(evt);
            }
        });

        txt_nama_paket.setEnabled(false);

        txt_harga_t.setEnabled(false);

        txt_jumlah_t.setText("1");
        txt_jumlah_t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlah_tKeyTyped(evt);
            }
        });

        jButton2.setText("Beli");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_transaksi);

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Total");

        txt_total_semua.setEditable(false);

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_id_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nama_paket)
                                .addComponent(tgl_transaksi)
                                .addComponent(cmb_kode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_no_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1))
                                .addComponent(txt_harga_t)
                                .addComponent(txt_jumlah_t))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(37, 37, 37)
                                .addComponent(txt_total_semua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgl_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_no_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_harga_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_jumlah_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel9)
                    .addComponent(txt_total_semua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        no_transaksi();
        tabel_transaksi();
        tampil_tabel_transaksi();
        txt_total_semua.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kodeActionPerformed
    
    public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = koneksi.getConnection();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = koneksi.getConnection();
        int row = tbl_transaksi.getSelectedRow();
        try {
            stt = con.createStatement();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Anda Belum Memilih Tabel");
            }
            else{
                int harga = Integer.parseInt((String) tbl_transaksi.getModel().getValueAt(row, 5));
                int total = Integer.parseInt(txt_total_semua.getText());
                String sql = "DELETE FROM detail_transaksi WHERE id_detail_transaksi = '"+tbl_transaksi.getModel().getValueAt(row, 0)+"'";
                stt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                txt_total_semua.setText(String.valueOf(total-harga));
                tabel_transaksi();
                tampil_tabel_transaksi();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmb_kodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kodeItemStateChanged
        Connection con = koneksi.getConnection();
        ResultSet rss2;
        String sql = "SELECT * FROM paket_makanan WHERE id_paket = '"+cmb_kode.getSelectedItem().toString()+"'";
        try {
            stt = con.createStatement();
            rss2 = stt.executeQuery(sql);
            if(rss2.next()){
                txt_nama_paket.setText(rss2.getString("nama_paket"));
                txt_harga_t.setText(rss2.getString("harga"));
            }
            rss2.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmb_kodeItemStateChanged

    private void txt_jumlah_tKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlah_tKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txt_jumlah_t.getText().length() < 10
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txt_jumlah_tKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = koneksi.getConnection();
        if(txt_jumlah_t.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data tidak boleh kosong");
        }
        else{
            int total = Integer.parseInt(txt_harga_t.getText()) * Integer.parseInt(txt_jumlah_t.getText());
            int simpan2 = 0;
            if(txt_total_semua.getText().equals("")){
                simpan2 = 0;
            }
            else
            simpan2 = Integer.valueOf(txt_total_semua.getText());

            String sql2 = "INSERT INTO detail_transaksi(id_transaksi,id_paket,harga,jumlah,total_harga) VALUES('"+txt_no_transaksi.getText()+"','"+cmb_kode.getSelectedItem().toString()+"','"+txt_harga_t.getText()+"','"+txt_jumlah_t.getText()+"','"+total+"')";
            try {
                simpan_no();
                stt2 = con.createStatement();
                stt2.executeUpdate(sql2);
                txt_total_semua.setText(String.valueOf(simpan2+total));
                JOptionPane.showMessageDialog(this, "Barang Berhasil Dibeli");
                tabel_transaksi();
                tampil_tabel_transaksi();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con = koneksi.getConnection();
        String NamaFile = "/com/tugasakhir/report/Struk_Pembayaran.jasper";
        HashMap hash = new HashMap();
        try {
            hash.put("idtransaksi", txt_no_transaksi.getText());
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_id_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_kasirActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        main mn = new main();
        this.setVisible(false);
        mn.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
//        private void tabel_makanan(){
//        model = new DefaultTableModel();
//        tbl_makanan.setModel(model);
//        model.addColumn("Id Paket Makanan");
//        model.addColumn("Nama Paket Makanan");
//        model.addColumn("Keterangan Paket");
//        model.addColumn("Harga");
//    }
    private void tampil_tabel(){
       Connection con = koneksi.getConnection();
       try {
           stt = con.createStatement();
           String sql = "SELECT * FROM paket_makanan";
           rss = stt.executeQuery(sql);
           while(rss.next()){
               Object[] o;
               o = new Object[4];
               o[0] = rss.getString("id_paket");
               o[1] = rss.getString("nama_paket");
               o[2] = rss.getString("keterangan");
               o[3] = rss.getString("harga");
               model.addRow(o);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    //FORM TRANSAKSI
    public void tglskrg(){
        Date skrg= new Date();
        SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
        SimpleDateFormat format2= new SimpleDateFormat("yyyy-MM-dd");
        tgl = format2.format(skrg);
        tgl_transaksi.setText(format.format(skrg));
    }
    public void no_transaksi(){
        Connection con = koneksi.getConnection();
        String sql = "SELECT id_transaksi FROM transaksi";
        try {
            stt = con.createStatement();
            rss = stt.executeQuery(sql);
            if(rss.last()){
                txt_no_transaksi.setText(String.valueOf(rss.getInt(1)+1));
            }
            else
                txt_no_transaksi.setText("1");
        } catch (Exception e) {
        }
    }
    public void kode_makanan(){
        Connection con = koneksi.getConnection();
        String sql = "SELECT * FROM paket_makanan";
        try {
         stt = con.createStatement();
         rss= stt.executeQuery(sql);
         while(rss.next()){
             cmb_kode.addItem(rss.getString("id_paket"));
         }
        } catch (Exception e) {
        }
    }
    private void tabel_transaksi(){
        model = new DefaultTableModel();
        tbl_transaksi.setModel(model);
        model.addColumn("Id Detail Transaksi");
        model.addColumn("No Transaksi");
        model.addColumn("Id paket");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total Harga");
    }
    private void tampil_tabel_transaksi(){
       Connection con = koneksi.getConnection();
       try {
           stt = con.createStatement();
           String sql = "SELECT * FROM detail_transaksi WHERE id_transaksi = '"+txt_no_transaksi.getText()+"'";
           rss = stt.executeQuery(sql);
           while(rss.next()){
               Object[] o;
               o = new Object[6];
               o[0] = rss.getString(1);
               o[1] = rss.getString(2);
               o[2] = rss.getString(3);
               o[3] = rss.getString(4);
               o[4] = rss.getString(5);
               o[5] = rss.getString(6);
               model.addRow(o);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    public void simpan_no(){
    Connection con = koneksi.getConnection();
        String sql = "INSERT INTO transaksi VALUES('"+txt_no_transaksi.getText()+"','"+txt_id_kasir.getText()+"','"+tgl+"')";
        try {
            stt = con.createStatement();
            stt.executeUpdate(sql);
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_kode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField tgl_transaksi;
    private javax.swing.JTextField txt_harga_t;
    private javax.swing.JTextField txt_id_kasir;
    private javax.swing.JTextField txt_jumlah_t;
    private javax.swing.JTextField txt_nama_paket;
    private javax.swing.JTextField txt_no_transaksi;
    private javax.swing.JTextField txt_total_semua;
    // End of variables declaration//GEN-END:variables
}
